/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ConsoleV1AutotunesIdGet404Response } from '../models';
// @ts-ignore
import type { ConsoleV1AutotunesPost400Response } from '../models';
// @ts-ignore
import type { ConsoleV1AutotunesPost401Response } from '../models';
// @ts-ignore
import type { ConsoleV1LayersIdDelete200Response } from '../models';
// @ts-ignore
import type { ConsoleV1LayersIdGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1LayersIdOverridesGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1LayersIdPatch200Response } from '../models';
// @ts-ignore
import type { ConsoleV1LayersIdPost200Response } from '../models';
// @ts-ignore
import type { ConsoleV1LayersPost201Response } from '../models';
// @ts-ignore
import type { Getconsolev1layersResponse } from '../models';
// @ts-ignore
import type { Getconsolev1layersidexperimentsResponse } from '../models';
// @ts-ignore
import type { LayerCreateContractDto } from '../models';
// @ts-ignore
import type { LayerFullUpdateContractDto } from '../models';
// @ts-ignore
import type { LayerOverridesDto } from '../models';
// @ts-ignore
import type { LayerOverridesPatchDto } from '../models';
// @ts-ignore
import type { LayerPartialUpdateContractDto } from '../models';
/**
 * LayersApi - axios parameter creator
 */
export const LayersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Layers
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersGet: async (limit?: number, page?: number, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/console/v1/layers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a layer
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdDelete: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1LayersIdDelete', 'id', id)
            const localVarPath = `/console/v1/layers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lineage: List Experiment related to Layer
         * @param {string} id id
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdExperimentsGet: async (id: string, limit?: number, page?: number, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1LayersIdExperimentsGet', 'id', id)
            const localVarPath = `/console/v1/layers/{id}/experiments`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get one layer
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdGet: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1LayersIdGet', 'id', id)
            const localVarPath = `/console/v1/layers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Layer Overrides
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdOverridesDelete: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1LayersIdOverridesDelete', 'id', id)
            const localVarPath = `/console/v1/layers/{id}/overrides`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Layer Overrides
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdOverridesGet: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1LayersIdOverridesGet', 'id', id)
            const localVarPath = `/console/v1/layers/{id}/overrides`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add Layer Overrides
         * @param {string} id id
         * @param {LayerOverridesPatchDto} layerOverridesPatchDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdOverridesPatch: async (id: string, layerOverridesPatchDto: LayerOverridesPatchDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1LayersIdOverridesPatch', 'id', id)
            // verify required parameter 'layerOverridesPatchDto' is not null or undefined
            assertParamExists('consoleV1LayersIdOverridesPatch', 'layerOverridesPatchDto', layerOverridesPatchDto)
            const localVarPath = `/console/v1/layers/{id}/overrides`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(layerOverridesPatchDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Layer Overrides
         * @param {string} id id
         * @param {LayerOverridesDto} layerOverridesDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdOverridesPost: async (id: string, layerOverridesDto: LayerOverridesDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1LayersIdOverridesPost', 'id', id)
            // verify required parameter 'layerOverridesDto' is not null or undefined
            assertParamExists('consoleV1LayersIdOverridesPost', 'layerOverridesDto', layerOverridesDto)
            const localVarPath = `/console/v1/layers/{id}/overrides`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(layerOverridesDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Partially update a layer
         * @param {string} id id
         * @param {LayerPartialUpdateContractDto} layerPartialUpdateContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdPatch: async (id: string, layerPartialUpdateContractDto: LayerPartialUpdateContractDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1LayersIdPatch', 'id', id)
            // verify required parameter 'layerPartialUpdateContractDto' is not null or undefined
            assertParamExists('consoleV1LayersIdPatch', 'layerPartialUpdateContractDto', layerPartialUpdateContractDto)
            const localVarPath = `/console/v1/layers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(layerPartialUpdateContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a layer
         * @param {string} id id
         * @param {LayerFullUpdateContractDto} layerFullUpdateContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdPost: async (id: string, layerFullUpdateContractDto: LayerFullUpdateContractDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1LayersIdPost', 'id', id)
            // verify required parameter 'layerFullUpdateContractDto' is not null or undefined
            assertParamExists('consoleV1LayersIdPost', 'layerFullUpdateContractDto', layerFullUpdateContractDto)
            const localVarPath = `/console/v1/layers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(layerFullUpdateContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a Layer
         * @param {LayerCreateContractDto} layerCreateContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersPost: async (layerCreateContractDto: LayerCreateContractDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'layerCreateContractDto' is not null or undefined
            assertParamExists('consoleV1LayersPost', 'layerCreateContractDto', layerCreateContractDto)
            const localVarPath = `/console/v1/layers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(layerCreateContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LayersApi - functional programming interface
 */
export const LayersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LayersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Layers
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1LayersGet(limit?: number, page?: number, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Getconsolev1layersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1LayersGet(limit, page, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LayersApi.consoleV1LayersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a layer
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1LayersIdDelete(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1LayersIdDelete200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1LayersIdDelete(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LayersApi.consoleV1LayersIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Lineage: List Experiment related to Layer
         * @param {string} id id
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1LayersIdExperimentsGet(id: string, limit?: number, page?: number, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Getconsolev1layersidexperimentsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1LayersIdExperimentsGet(id, limit, page, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LayersApi.consoleV1LayersIdExperimentsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get one layer
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1LayersIdGet(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1LayersIdGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1LayersIdGet(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LayersApi.consoleV1LayersIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Layer Overrides
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1LayersIdOverridesDelete(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1LayersIdOverridesGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1LayersIdOverridesDelete(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LayersApi.consoleV1LayersIdOverridesDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Layer Overrides
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1LayersIdOverridesGet(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1LayersIdOverridesGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1LayersIdOverridesGet(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LayersApi.consoleV1LayersIdOverridesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Add Layer Overrides
         * @param {string} id id
         * @param {LayerOverridesPatchDto} layerOverridesPatchDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1LayersIdOverridesPatch(id: string, layerOverridesPatchDto: LayerOverridesPatchDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1LayersIdOverridesGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1LayersIdOverridesPatch(id, layerOverridesPatchDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LayersApi.consoleV1LayersIdOverridesPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Layer Overrides
         * @param {string} id id
         * @param {LayerOverridesDto} layerOverridesDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1LayersIdOverridesPost(id: string, layerOverridesDto: LayerOverridesDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1LayersIdOverridesGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1LayersIdOverridesPost(id, layerOverridesDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LayersApi.consoleV1LayersIdOverridesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Partially update a layer
         * @param {string} id id
         * @param {LayerPartialUpdateContractDto} layerPartialUpdateContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1LayersIdPatch(id: string, layerPartialUpdateContractDto: LayerPartialUpdateContractDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1LayersIdPatch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1LayersIdPatch(id, layerPartialUpdateContractDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LayersApi.consoleV1LayersIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a layer
         * @param {string} id id
         * @param {LayerFullUpdateContractDto} layerFullUpdateContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1LayersIdPost(id: string, layerFullUpdateContractDto: LayerFullUpdateContractDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1LayersIdPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1LayersIdPost(id, layerFullUpdateContractDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LayersApi.consoleV1LayersIdPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a Layer
         * @param {LayerCreateContractDto} layerCreateContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1LayersPost(layerCreateContractDto: LayerCreateContractDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1LayersPost201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1LayersPost(layerCreateContractDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LayersApi.consoleV1LayersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LayersApi - factory interface
 */
export const LayersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LayersApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Layers
         * @param {LayersApiConsoleV1LayersGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersGet(requestParameters: LayersApiConsoleV1LayersGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Getconsolev1layersResponse> {
            return localVarFp.consoleV1LayersGet(requestParameters.limit, requestParameters.page, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a layer
         * @param {LayersApiConsoleV1LayersIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdDelete(requestParameters: LayersApiConsoleV1LayersIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1LayersIdDelete200Response> {
            return localVarFp.consoleV1LayersIdDelete(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lineage: List Experiment related to Layer
         * @param {LayersApiConsoleV1LayersIdExperimentsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdExperimentsGet(requestParameters: LayersApiConsoleV1LayersIdExperimentsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Getconsolev1layersidexperimentsResponse> {
            return localVarFp.consoleV1LayersIdExperimentsGet(requestParameters.id, requestParameters.limit, requestParameters.page, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get one layer
         * @param {LayersApiConsoleV1LayersIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdGet(requestParameters: LayersApiConsoleV1LayersIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1LayersIdGet200Response> {
            return localVarFp.consoleV1LayersIdGet(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Layer Overrides
         * @param {LayersApiConsoleV1LayersIdOverridesDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdOverridesDelete(requestParameters: LayersApiConsoleV1LayersIdOverridesDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1LayersIdOverridesGet200Response> {
            return localVarFp.consoleV1LayersIdOverridesDelete(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Layer Overrides
         * @param {LayersApiConsoleV1LayersIdOverridesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdOverridesGet(requestParameters: LayersApiConsoleV1LayersIdOverridesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1LayersIdOverridesGet200Response> {
            return localVarFp.consoleV1LayersIdOverridesGet(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add Layer Overrides
         * @param {LayersApiConsoleV1LayersIdOverridesPatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdOverridesPatch(requestParameters: LayersApiConsoleV1LayersIdOverridesPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1LayersIdOverridesGet200Response> {
            return localVarFp.consoleV1LayersIdOverridesPatch(requestParameters.id, requestParameters.layerOverridesPatchDto, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Layer Overrides
         * @param {LayersApiConsoleV1LayersIdOverridesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdOverridesPost(requestParameters: LayersApiConsoleV1LayersIdOverridesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1LayersIdOverridesGet200Response> {
            return localVarFp.consoleV1LayersIdOverridesPost(requestParameters.id, requestParameters.layerOverridesDto, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Partially update a layer
         * @param {LayersApiConsoleV1LayersIdPatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdPatch(requestParameters: LayersApiConsoleV1LayersIdPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1LayersIdPatch200Response> {
            return localVarFp.consoleV1LayersIdPatch(requestParameters.id, requestParameters.layerPartialUpdateContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a layer
         * @param {LayersApiConsoleV1LayersIdPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersIdPost(requestParameters: LayersApiConsoleV1LayersIdPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1LayersIdPost200Response> {
            return localVarFp.consoleV1LayersIdPost(requestParameters.id, requestParameters.layerFullUpdateContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a Layer
         * @param {LayersApiConsoleV1LayersPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1LayersPost(requestParameters: LayersApiConsoleV1LayersPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1LayersPost201Response> {
            return localVarFp.consoleV1LayersPost(requestParameters.layerCreateContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for consoleV1LayersGet operation in LayersApi.
 */
export interface LayersApiConsoleV1LayersGetRequest {
    /**
     * Results per page
     */
    readonly limit?: number

    /**
     * Page number
     */
    readonly page?: number

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1LayersIdDelete operation in LayersApi.
 */
export interface LayersApiConsoleV1LayersIdDeleteRequest {
    /**
     * id
     */
    readonly id: string

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1LayersIdExperimentsGet operation in LayersApi.
 */
export interface LayersApiConsoleV1LayersIdExperimentsGetRequest {
    /**
     * id
     */
    readonly id: string

    /**
     * Results per page
     */
    readonly limit?: number

    /**
     * Page number
     */
    readonly page?: number

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1LayersIdGet operation in LayersApi.
 */
export interface LayersApiConsoleV1LayersIdGetRequest {
    /**
     * id
     */
    readonly id: string

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1LayersIdOverridesDelete operation in LayersApi.
 */
export interface LayersApiConsoleV1LayersIdOverridesDeleteRequest {
    /**
     * id
     */
    readonly id: string

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1LayersIdOverridesGet operation in LayersApi.
 */
export interface LayersApiConsoleV1LayersIdOverridesGetRequest {
    /**
     * id
     */
    readonly id: string

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1LayersIdOverridesPatch operation in LayersApi.
 */
export interface LayersApiConsoleV1LayersIdOverridesPatchRequest {
    /**
     * id
     */
    readonly id: string

    readonly layerOverridesPatchDto: LayerOverridesPatchDto

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1LayersIdOverridesPost operation in LayersApi.
 */
export interface LayersApiConsoleV1LayersIdOverridesPostRequest {
    /**
     * id
     */
    readonly id: string

    readonly layerOverridesDto: LayerOverridesDto

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1LayersIdPatch operation in LayersApi.
 */
export interface LayersApiConsoleV1LayersIdPatchRequest {
    /**
     * id
     */
    readonly id: string

    readonly layerPartialUpdateContractDto: LayerPartialUpdateContractDto

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1LayersIdPost operation in LayersApi.
 */
export interface LayersApiConsoleV1LayersIdPostRequest {
    /**
     * id
     */
    readonly id: string

    readonly layerFullUpdateContractDto: LayerFullUpdateContractDto

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1LayersPost operation in LayersApi.
 */
export interface LayersApiConsoleV1LayersPostRequest {
    readonly layerCreateContractDto: LayerCreateContractDto

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * LayersApi - object-oriented interface
 */
export class LayersApi extends BaseAPI {
    /**
     * 
     * @summary Get Layers
     * @param {LayersApiConsoleV1LayersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1LayersGet(requestParameters: LayersApiConsoleV1LayersGetRequest = {}, options?: RawAxiosRequestConfig) {
        return LayersApiFp(this.configuration).consoleV1LayersGet(requestParameters.limit, requestParameters.page, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a layer
     * @param {LayersApiConsoleV1LayersIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1LayersIdDelete(requestParameters: LayersApiConsoleV1LayersIdDeleteRequest, options?: RawAxiosRequestConfig) {
        return LayersApiFp(this.configuration).consoleV1LayersIdDelete(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Lineage: List Experiment related to Layer
     * @param {LayersApiConsoleV1LayersIdExperimentsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1LayersIdExperimentsGet(requestParameters: LayersApiConsoleV1LayersIdExperimentsGetRequest, options?: RawAxiosRequestConfig) {
        return LayersApiFp(this.configuration).consoleV1LayersIdExperimentsGet(requestParameters.id, requestParameters.limit, requestParameters.page, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get one layer
     * @param {LayersApiConsoleV1LayersIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1LayersIdGet(requestParameters: LayersApiConsoleV1LayersIdGetRequest, options?: RawAxiosRequestConfig) {
        return LayersApiFp(this.configuration).consoleV1LayersIdGet(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Layer Overrides
     * @param {LayersApiConsoleV1LayersIdOverridesDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1LayersIdOverridesDelete(requestParameters: LayersApiConsoleV1LayersIdOverridesDeleteRequest, options?: RawAxiosRequestConfig) {
        return LayersApiFp(this.configuration).consoleV1LayersIdOverridesDelete(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Layer Overrides
     * @param {LayersApiConsoleV1LayersIdOverridesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1LayersIdOverridesGet(requestParameters: LayersApiConsoleV1LayersIdOverridesGetRequest, options?: RawAxiosRequestConfig) {
        return LayersApiFp(this.configuration).consoleV1LayersIdOverridesGet(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Add Layer Overrides
     * @param {LayersApiConsoleV1LayersIdOverridesPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1LayersIdOverridesPatch(requestParameters: LayersApiConsoleV1LayersIdOverridesPatchRequest, options?: RawAxiosRequestConfig) {
        return LayersApiFp(this.configuration).consoleV1LayersIdOverridesPatch(requestParameters.id, requestParameters.layerOverridesPatchDto, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Layer Overrides
     * @param {LayersApiConsoleV1LayersIdOverridesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1LayersIdOverridesPost(requestParameters: LayersApiConsoleV1LayersIdOverridesPostRequest, options?: RawAxiosRequestConfig) {
        return LayersApiFp(this.configuration).consoleV1LayersIdOverridesPost(requestParameters.id, requestParameters.layerOverridesDto, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Partially update a layer
     * @param {LayersApiConsoleV1LayersIdPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1LayersIdPatch(requestParameters: LayersApiConsoleV1LayersIdPatchRequest, options?: RawAxiosRequestConfig) {
        return LayersApiFp(this.configuration).consoleV1LayersIdPatch(requestParameters.id, requestParameters.layerPartialUpdateContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a layer
     * @param {LayersApiConsoleV1LayersIdPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1LayersIdPost(requestParameters: LayersApiConsoleV1LayersIdPostRequest, options?: RawAxiosRequestConfig) {
        return LayersApiFp(this.configuration).consoleV1LayersIdPost(requestParameters.id, requestParameters.layerFullUpdateContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a Layer
     * @param {LayersApiConsoleV1LayersPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1LayersPost(requestParameters: LayersApiConsoleV1LayersPostRequest, options?: RawAxiosRequestConfig) {
        return LayersApiFp(this.configuration).consoleV1LayersPost(requestParameters.layerCreateContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }
}

