/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ConsoleV1ReleasePipelineTriggersGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1ReleasePipelineTriggersGetStatusParameter } from '../models';
// @ts-ignore
import type { ConsoleV1ReleasePipelineTriggersIdAbortPut200Response } from '../models';
// @ts-ignore
import type { ConsoleV1ReleasePipelineTriggersIdGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1ReleasePipelinesGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1ReleasePipelinesIdDelete200Response } from '../models';
// @ts-ignore
import type { ConsoleV1ReleasePipelinesPost200Response } from '../models';
// @ts-ignore
import type { ReleasePipelineCreateDto } from '../models';
// @ts-ignore
import type { ReleasePipelineTriggerActionBodyDto } from '../models';
// @ts-ignore
import type { ReleasePipelineUpdateDto } from '../models';
/**
 * ReleasePipelinesApi - axios parameter creator
 */
export const ReleasePipelinesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List Pipeline Triggers
         * @param {string} [releasePipelineID] Filter by Release Pipeline ID
         * @param {string} [gateID] Filter by Gate ID
         * @param {string} [dynamicConfigID] Filter by Dynamic Config ID
         * @param {ConsoleV1ReleasePipelineTriggersGetStatusParameter} [status] Filter by Status
         * @param {string} [startDate] Filter by the start date of the date range of the trigger\&#39;s creation date in UTC, inclusive
         * @param {string} [endDate] Filter by the end date of the date range of the trigger\&#39;s creation date in UTC, inclusive (i.e. until the end of the day); defaults to today\&#39;s date if not provided
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersGet: async (releasePipelineID?: string, gateID?: string, dynamicConfigID?: string, status?: ConsoleV1ReleasePipelineTriggersGetStatusParameter, startDate?: string, endDate?: string, limit?: number, page?: number, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/console/v1/release_pipeline_triggers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            if (releasePipelineID !== undefined) {
                localVarQueryParameter['releasePipelineID'] = releasePipelineID;
            }

            if (gateID !== undefined) {
                localVarQueryParameter['gateID'] = gateID;
            }

            if (dynamicConfigID !== undefined) {
                localVarQueryParameter['dynamicConfigID'] = dynamicConfigID;
            }

            if (status !== undefined) {
                for (const [key, value] of Object.entries(status)) {
                    localVarQueryParameter[key] = value;
                }
            }

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = endDate;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Abort Pipeline Trigger
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdAbortPut: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1ReleasePipelineTriggersIdAbortPut', 'id', id)
            const localVarPath = `/console/v1/release_pipeline_triggers/{id}/abort`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Approve Pipeline Trigger Phase
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdApprovePut: async (id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1ReleasePipelineTriggersIdApprovePut', 'id', id)
            // verify required parameter 'releasePipelineTriggerActionBodyDto' is not null or undefined
            assertParamExists('consoleV1ReleasePipelineTriggersIdApprovePut', 'releasePipelineTriggerActionBodyDto', releasePipelineTriggerActionBodyDto)
            const localVarPath = `/console/v1/release_pipeline_triggers/{id}/approve`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(releasePipelineTriggerActionBodyDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Pipeline Trigger
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdGet: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1ReleasePipelineTriggersIdGet', 'id', id)
            const localVarPath = `/console/v1/release_pipeline_triggers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Pause Pipeline Trigger
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdPausePut: async (id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1ReleasePipelineTriggersIdPausePut', 'id', id)
            // verify required parameter 'releasePipelineTriggerActionBodyDto' is not null or undefined
            assertParamExists('consoleV1ReleasePipelineTriggersIdPausePut', 'releasePipelineTriggerActionBodyDto', releasePipelineTriggerActionBodyDto)
            const localVarPath = `/console/v1/release_pipeline_triggers/{id}/pause`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(releasePipelineTriggerActionBodyDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Fully Roll Out Pipeline Trigger
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdRolloutPut: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1ReleasePipelineTriggersIdRolloutPut', 'id', id)
            const localVarPath = `/console/v1/release_pipeline_triggers/{id}/rollout`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Skip to Pipeline Trigger Phase
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdSkipPut: async (id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1ReleasePipelineTriggersIdSkipPut', 'id', id)
            // verify required parameter 'releasePipelineTriggerActionBodyDto' is not null or undefined
            assertParamExists('consoleV1ReleasePipelineTriggersIdSkipPut', 'releasePipelineTriggerActionBodyDto', releasePipelineTriggerActionBodyDto)
            const localVarPath = `/console/v1/release_pipeline_triggers/{id}/skip`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(releasePipelineTriggerActionBodyDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Unpause Pipeline Trigger
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdUnpausePut: async (id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1ReleasePipelineTriggersIdUnpausePut', 'id', id)
            // verify required parameter 'releasePipelineTriggerActionBodyDto' is not null or undefined
            assertParamExists('consoleV1ReleasePipelineTriggersIdUnpausePut', 'releasePipelineTriggerActionBodyDto', releasePipelineTriggerActionBodyDto)
            const localVarPath = `/console/v1/release_pipeline_triggers/{id}/unpause`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(releasePipelineTriggerActionBodyDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Pipelines
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelinesGet: async (limit?: number, page?: number, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/console/v1/release_pipelines`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Pipeline
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelinesIdDelete: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1ReleasePipelinesIdDelete', 'id', id)
            const localVarPath = `/console/v1/release_pipelines/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Pipeline
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelinesIdGet: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1ReleasePipelinesIdGet', 'id', id)
            const localVarPath = `/console/v1/release_pipelines/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Pipeline
         * @param {string} id 
         * @param {ReleasePipelineUpdateDto} releasePipelineUpdateDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelinesIdPost: async (id: string, releasePipelineUpdateDto: ReleasePipelineUpdateDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1ReleasePipelinesIdPost', 'id', id)
            // verify required parameter 'releasePipelineUpdateDto' is not null or undefined
            assertParamExists('consoleV1ReleasePipelinesIdPost', 'releasePipelineUpdateDto', releasePipelineUpdateDto)
            const localVarPath = `/console/v1/release_pipelines/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(releasePipelineUpdateDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create Pipeline
         * @param {ReleasePipelineCreateDto} releasePipelineCreateDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelinesPost: async (releasePipelineCreateDto: ReleasePipelineCreateDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'releasePipelineCreateDto' is not null or undefined
            assertParamExists('consoleV1ReleasePipelinesPost', 'releasePipelineCreateDto', releasePipelineCreateDto)
            const localVarPath = `/console/v1/release_pipelines`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(releasePipelineCreateDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReleasePipelinesApi - functional programming interface
 */
export const ReleasePipelinesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReleasePipelinesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List Pipeline Triggers
         * @param {string} [releasePipelineID] Filter by Release Pipeline ID
         * @param {string} [gateID] Filter by Gate ID
         * @param {string} [dynamicConfigID] Filter by Dynamic Config ID
         * @param {ConsoleV1ReleasePipelineTriggersGetStatusParameter} [status] Filter by Status
         * @param {string} [startDate] Filter by the start date of the date range of the trigger\&#39;s creation date in UTC, inclusive
         * @param {string} [endDate] Filter by the end date of the date range of the trigger\&#39;s creation date in UTC, inclusive (i.e. until the end of the day); defaults to today\&#39;s date if not provided
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelineTriggersGet(releasePipelineID?: string, gateID?: string, dynamicConfigID?: string, status?: ConsoleV1ReleasePipelineTriggersGetStatusParameter, startDate?: string, endDate?: string, limit?: number, page?: number, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelineTriggersGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelineTriggersGet(releasePipelineID, gateID, dynamicConfigID, status, startDate, endDate, limit, page, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelineTriggersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Abort Pipeline Trigger
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelineTriggersIdAbortPut(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelineTriggersIdAbortPut(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelineTriggersIdAbortPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Approve Pipeline Trigger Phase
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelineTriggersIdApprovePut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelineTriggersIdApprovePut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelineTriggersIdApprovePut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Pipeline Trigger
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelineTriggersIdGet(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelineTriggersIdGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelineTriggersIdGet(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelineTriggersIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Pause Pipeline Trigger
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelineTriggersIdPausePut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelineTriggersIdPausePut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelineTriggersIdPausePut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Fully Roll Out Pipeline Trigger
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelineTriggersIdRolloutPut(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelineTriggersIdRolloutPut(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelineTriggersIdRolloutPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Skip to Pipeline Trigger Phase
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelineTriggersIdSkipPut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelineTriggersIdSkipPut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelineTriggersIdSkipPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Unpause Pipeline Trigger
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelineTriggersIdUnpausePut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelineTriggersIdUnpausePut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelineTriggersIdUnpausePut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Pipelines
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelinesGet(limit?: number, page?: number, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelinesGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelinesGet(limit, page, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelinesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Pipeline
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelinesIdDelete(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelinesIdDelete200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelinesIdDelete(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelinesIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Pipeline
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelinesIdGet(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelinesPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelinesIdGet(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelinesIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Pipeline
         * @param {string} id 
         * @param {ReleasePipelineUpdateDto} releasePipelineUpdateDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelinesIdPost(id: string, releasePipelineUpdateDto: ReleasePipelineUpdateDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelinesPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelinesIdPost(id, releasePipelineUpdateDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelinesIdPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create Pipeline
         * @param {ReleasePipelineCreateDto} releasePipelineCreateDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1ReleasePipelinesPost(releasePipelineCreateDto: ReleasePipelineCreateDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1ReleasePipelinesPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1ReleasePipelinesPost(releasePipelineCreateDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePipelinesApi.consoleV1ReleasePipelinesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReleasePipelinesApi - factory interface
 */
export const ReleasePipelinesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReleasePipelinesApiFp(configuration)
    return {
        /**
         * 
         * @summary List Pipeline Triggers
         * @param {string} [releasePipelineID] Filter by Release Pipeline ID
         * @param {string} [gateID] Filter by Gate ID
         * @param {string} [dynamicConfigID] Filter by Dynamic Config ID
         * @param {ConsoleV1ReleasePipelineTriggersGetStatusParameter} [status] Filter by Status
         * @param {string} [startDate] Filter by the start date of the date range of the trigger\&#39;s creation date in UTC, inclusive
         * @param {string} [endDate] Filter by the end date of the date range of the trigger\&#39;s creation date in UTC, inclusive (i.e. until the end of the day); defaults to today\&#39;s date if not provided
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersGet(releasePipelineID?: string, gateID?: string, dynamicConfigID?: string, status?: ConsoleV1ReleasePipelineTriggersGetStatusParameter, startDate?: string, endDate?: string, limit?: number, page?: number, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelineTriggersGet200Response> {
            return localVarFp.consoleV1ReleasePipelineTriggersGet(releasePipelineID, gateID, dynamicConfigID, status, startDate, endDate, limit, page, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Abort Pipeline Trigger
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdAbortPut(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response> {
            return localVarFp.consoleV1ReleasePipelineTriggersIdAbortPut(id, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Approve Pipeline Trigger Phase
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdApprovePut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response> {
            return localVarFp.consoleV1ReleasePipelineTriggersIdApprovePut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Pipeline Trigger
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdGet(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelineTriggersIdGet200Response> {
            return localVarFp.consoleV1ReleasePipelineTriggersIdGet(id, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Pause Pipeline Trigger
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdPausePut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response> {
            return localVarFp.consoleV1ReleasePipelineTriggersIdPausePut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Fully Roll Out Pipeline Trigger
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdRolloutPut(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response> {
            return localVarFp.consoleV1ReleasePipelineTriggersIdRolloutPut(id, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Skip to Pipeline Trigger Phase
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdSkipPut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response> {
            return localVarFp.consoleV1ReleasePipelineTriggersIdSkipPut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Unpause Pipeline Trigger
         * @param {string} id 
         * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelineTriggersIdUnpausePut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelineTriggersIdAbortPut200Response> {
            return localVarFp.consoleV1ReleasePipelineTriggersIdUnpausePut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Pipelines
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelinesGet(limit?: number, page?: number, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelinesGet200Response> {
            return localVarFp.consoleV1ReleasePipelinesGet(limit, page, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Pipeline
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelinesIdDelete(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelinesIdDelete200Response> {
            return localVarFp.consoleV1ReleasePipelinesIdDelete(id, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Pipeline
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelinesIdGet(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelinesPost200Response> {
            return localVarFp.consoleV1ReleasePipelinesIdGet(id, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Pipeline
         * @param {string} id 
         * @param {ReleasePipelineUpdateDto} releasePipelineUpdateDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelinesIdPost(id: string, releasePipelineUpdateDto: ReleasePipelineUpdateDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelinesPost200Response> {
            return localVarFp.consoleV1ReleasePipelinesIdPost(id, releasePipelineUpdateDto, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create Pipeline
         * @param {ReleasePipelineCreateDto} releasePipelineCreateDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1ReleasePipelinesPost(releasePipelineCreateDto: ReleasePipelineCreateDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1ReleasePipelinesPost200Response> {
            return localVarFp.consoleV1ReleasePipelinesPost(releasePipelineCreateDto, xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReleasePipelinesApi - object-oriented interface
 */
export class ReleasePipelinesApi extends BaseAPI {
    /**
     * 
     * @summary List Pipeline Triggers
     * @param {string} [releasePipelineID] Filter by Release Pipeline ID
     * @param {string} [gateID] Filter by Gate ID
     * @param {string} [dynamicConfigID] Filter by Dynamic Config ID
     * @param {ConsoleV1ReleasePipelineTriggersGetStatusParameter} [status] Filter by Status
     * @param {string} [startDate] Filter by the start date of the date range of the trigger\&#39;s creation date in UTC, inclusive
     * @param {string} [endDate] Filter by the end date of the date range of the trigger\&#39;s creation date in UTC, inclusive (i.e. until the end of the day); defaults to today\&#39;s date if not provided
     * @param {number} [limit] Results per page
     * @param {number} [page] Page number
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelineTriggersGet(releasePipelineID?: string, gateID?: string, dynamicConfigID?: string, status?: ConsoleV1ReleasePipelineTriggersGetStatusParameter, startDate?: string, endDate?: string, limit?: number, page?: number, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelineTriggersGet(releasePipelineID, gateID, dynamicConfigID, status, startDate, endDate, limit, page, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Abort Pipeline Trigger
     * @param {string} id 
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelineTriggersIdAbortPut(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelineTriggersIdAbortPut(id, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Approve Pipeline Trigger Phase
     * @param {string} id 
     * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelineTriggersIdApprovePut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelineTriggersIdApprovePut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Pipeline Trigger
     * @param {string} id 
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelineTriggersIdGet(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelineTriggersIdGet(id, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Pause Pipeline Trigger
     * @param {string} id 
     * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelineTriggersIdPausePut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelineTriggersIdPausePut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Fully Roll Out Pipeline Trigger
     * @param {string} id 
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelineTriggersIdRolloutPut(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelineTriggersIdRolloutPut(id, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Skip to Pipeline Trigger Phase
     * @param {string} id 
     * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelineTriggersIdSkipPut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelineTriggersIdSkipPut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Unpause Pipeline Trigger
     * @param {string} id 
     * @param {ReleasePipelineTriggerActionBodyDto} releasePipelineTriggerActionBodyDto 
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelineTriggersIdUnpausePut(id: string, releasePipelineTriggerActionBodyDto: ReleasePipelineTriggerActionBodyDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelineTriggersIdUnpausePut(id, releasePipelineTriggerActionBodyDto, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Pipelines
     * @param {number} [limit] Results per page
     * @param {number} [page] Page number
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelinesGet(limit?: number, page?: number, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelinesGet(limit, page, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Pipeline
     * @param {string} id 
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelinesIdDelete(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelinesIdDelete(id, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Pipeline
     * @param {string} id 
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelinesIdGet(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelinesIdGet(id, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Pipeline
     * @param {string} id 
     * @param {ReleasePipelineUpdateDto} releasePipelineUpdateDto 
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelinesIdPost(id: string, releasePipelineUpdateDto: ReleasePipelineUpdateDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelinesIdPost(id, releasePipelineUpdateDto, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create Pipeline
     * @param {ReleasePipelineCreateDto} releasePipelineCreateDto 
     * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1ReleasePipelinesPost(releasePipelineCreateDto: ReleasePipelineCreateDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig) {
        return ReleasePipelinesApiFp(this.configuration).consoleV1ReleasePipelinesPost(releasePipelineCreateDto, xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }
}

