/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ConsoleV1AutotunesIdGet404Response } from '../models';
// @ts-ignore
import type { ConsoleV1AutotunesPost400Response } from '../models';
// @ts-ignore
import type { ConsoleV1AutotunesPost401Response } from '../models';
// @ts-ignore
import type { ConsoleV1SegmentsIdAddIdsPatch200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SegmentsIdArchivePut200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SegmentsIdConditionalPost200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SegmentsIdDelete200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SegmentsIdGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SegmentsIdIdListDelete200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SegmentsIdIdListGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SegmentsIdIdListResetPost200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SegmentsIdIdlistMetadataGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SegmentsIdReviewsReviewIDCommitPut200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SegmentsPost201Response } from '../models';
// @ts-ignore
import type { Getconsolev1segmentsResponse } from '../models';
// @ts-ignore
import type { SegmentCreateContractDto } from '../models';
// @ts-ignore
import type { SegmentCreateContractDtoRulesInner } from '../models';
// @ts-ignore
import type { SegmentIDListContractDto } from '../models';
// @ts-ignore
import type { SegmentIDListResetContractDto } from '../models';
// @ts-ignore
import type { SegmentIDListUserStoreContractDto } from '../models';
/**
 * SegmentsApi - axios parameter creator
 */
export const SegmentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List Segments
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsGet: async (limit?: number, page?: number, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/console/v1/segments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint has a limit of 1000 ids per request
         * @summary Add IDs to User Store ID List
         * @param {string} id id
         * @param {SegmentIDListUserStoreContractDto} segmentIDListUserStoreContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdAddIdsPatch: async (id: string, segmentIDListUserStoreContractDto: SegmentIDListUserStoreContractDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdAddIdsPatch', 'id', id)
            // verify required parameter 'segmentIDListUserStoreContractDto' is not null or undefined
            assertParamExists('consoleV1SegmentsIdAddIdsPatch', 'segmentIDListUserStoreContractDto', segmentIDListUserStoreContractDto)
            const localVarPath = `/console/v1/segments/{id}/add_ids`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(segmentIDListUserStoreContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Archive Segment
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdArchivePut: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdArchivePut', 'id', id)
            const localVarPath = `/console/v1/segments/{id}/archive`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Segment Rules
         * @param {string} id id
         * @param {Array<SegmentCreateContractDtoRulesInner>} segmentCreateContractDtoRulesInner 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdConditionalPost: async (id: string, segmentCreateContractDtoRulesInner: Array<SegmentCreateContractDtoRulesInner>, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdConditionalPost', 'id', id)
            // verify required parameter 'segmentCreateContractDtoRulesInner' is not null or undefined
            assertParamExists('consoleV1SegmentsIdConditionalPost', 'segmentCreateContractDtoRulesInner', segmentCreateContractDtoRulesInner)
            const localVarPath = `/console/v1/segments/{id}/conditional`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(segmentCreateContractDtoRulesInner, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Segment
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdDelete: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdDelete', 'id', id)
            const localVarPath = `/console/v1/segments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Segment
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdGet: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdGet', 'id', id)
            const localVarPath = `/console/v1/segments/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint is rate limited to 900 requests /15m or 12 requests /10s.
         * @summary Remove IDs from Segment
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdIdListDelete: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdIdListDelete', 'id', id)
            const localVarPath = `/console/v1/segments/{id}/id_list`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint is rate limited to 100
         * @summary Get IDs in a Segment
         * @param {string} id 
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdIdListGet: async (id: string, limit?: number, page?: number, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdIdListGet', 'id', id)
            const localVarPath = `/console/v1/segments/{id}/id_list`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint is rate limited to 900 requests /15m or 12 requests /10s.
         * @summary Add IDs to Segment
         * @param {string} id id
         * @param {SegmentIDListContractDto} segmentIDListContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdIdListPatch: async (id: string, segmentIDListContractDto: SegmentIDListContractDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdIdListPatch', 'id', id)
            // verify required parameter 'segmentIDListContractDto' is not null or undefined
            assertParamExists('consoleV1SegmentsIdIdListPatch', 'segmentIDListContractDto', segmentIDListContractDto)
            const localVarPath = `/console/v1/segments/{id}/id_list`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(segmentIDListContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Warning: Not atomic for big ID lists (> 1000)
         * @summary Reset ID List Segment
         * @param {string} id id
         * @param {SegmentIDListResetContractDto} segmentIDListResetContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdIdListResetPost: async (id: string, segmentIDListResetContractDto: SegmentIDListResetContractDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdIdListResetPost', 'id', id)
            // verify required parameter 'segmentIDListResetContractDto' is not null or undefined
            assertParamExists('consoleV1SegmentsIdIdListResetPost', 'segmentIDListResetContractDto', segmentIDListResetContractDto)
            const localVarPath = `/console/v1/segments/{id}/id_list/reset`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(segmentIDListResetContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint gets the metadata of the ID List.
         * @summary Get ID List Metadata
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdIdlistMetadataGet: async (id: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdIdlistMetadataGet', 'id', id)
            const localVarPath = `/console/v1/segments/{id}/idlist_metadata`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint has a limit of 1000 ids per request
         * @summary Remove IDs from User Store ID List
         * @param {string} id id
         * @param {SegmentIDListUserStoreContractDto} segmentIDListUserStoreContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdRemoveIdsPatch: async (id: string, segmentIDListUserStoreContractDto: SegmentIDListUserStoreContractDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdRemoveIdsPatch', 'id', id)
            // verify required parameter 'segmentIDListUserStoreContractDto' is not null or undefined
            assertParamExists('consoleV1SegmentsIdRemoveIdsPatch', 'segmentIDListUserStoreContractDto', segmentIDListUserStoreContractDto)
            const localVarPath = `/console/v1/segments/{id}/remove_ids`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(segmentIDListUserStoreContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Commit Segment Review
         * @param {string} id 
         * @param {string} reviewID 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdReviewsReviewIDCommitPut: async (id: string, reviewID: string, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('consoleV1SegmentsIdReviewsReviewIDCommitPut', 'id', id)
            // verify required parameter 'reviewID' is not null or undefined
            assertParamExists('consoleV1SegmentsIdReviewsReviewIDCommitPut', 'reviewID', reviewID)
            const localVarPath = `/console/v1/segments/{id}/reviews/{reviewID}/commit`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"reviewID"}}`, encodeURIComponent(String(reviewID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create Segment
         * @param {SegmentCreateContractDto} segmentCreateContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsPost: async (segmentCreateContractDto: SegmentCreateContractDto, xRespectReviewSettings?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'segmentCreateContractDto' is not null or undefined
            assertParamExists('consoleV1SegmentsPost', 'segmentCreateContractDto', segmentCreateContractDto)
            const localVarPath = `/console/v1/segments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xRespectReviewSettings != null) {
                localVarHeaderParameter['x-respect-review-settings'] = String(xRespectReviewSettings);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(segmentCreateContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SegmentsApi - functional programming interface
 */
export const SegmentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SegmentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List Segments
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsGet(limit?: number, page?: number, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Getconsolev1segmentsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsGet(limit, page, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint has a limit of 1000 ids per request
         * @summary Add IDs to User Store ID List
         * @param {string} id id
         * @param {SegmentIDListUserStoreContractDto} segmentIDListUserStoreContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdAddIdsPatch(id: string, segmentIDListUserStoreContractDto: SegmentIDListUserStoreContractDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdAddIdsPatch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdAddIdsPatch(id, segmentIDListUserStoreContractDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdAddIdsPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Archive Segment
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdArchivePut(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdArchivePut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdArchivePut(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdArchivePut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Segment Rules
         * @param {string} id id
         * @param {Array<SegmentCreateContractDtoRulesInner>} segmentCreateContractDtoRulesInner 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdConditionalPost(id: string, segmentCreateContractDtoRulesInner: Array<SegmentCreateContractDtoRulesInner>, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdConditionalPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdConditionalPost(id, segmentCreateContractDtoRulesInner, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdConditionalPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Segment
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdDelete(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdDelete200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdDelete(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Segment
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdGet(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdGet(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint is rate limited to 900 requests /15m or 12 requests /10s.
         * @summary Remove IDs from Segment
         * @param {string} id id
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdIdListDelete(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdIdListDelete200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdIdListDelete(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdIdListDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint is rate limited to 100
         * @summary Get IDs in a Segment
         * @param {string} id 
         * @param {number} [limit] Results per page
         * @param {number} [page] Page number
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdIdListGet(id: string, limit?: number, page?: number, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdIdListGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdIdListGet(id, limit, page, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdIdListGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint is rate limited to 900 requests /15m or 12 requests /10s.
         * @summary Add IDs to Segment
         * @param {string} id id
         * @param {SegmentIDListContractDto} segmentIDListContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdIdListPatch(id: string, segmentIDListContractDto: SegmentIDListContractDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdAddIdsPatch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdIdListPatch(id, segmentIDListContractDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdIdListPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Warning: Not atomic for big ID lists (> 1000)
         * @summary Reset ID List Segment
         * @param {string} id id
         * @param {SegmentIDListResetContractDto} segmentIDListResetContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdIdListResetPost(id: string, segmentIDListResetContractDto: SegmentIDListResetContractDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdIdListResetPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdIdListResetPost(id, segmentIDListResetContractDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdIdListResetPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint gets the metadata of the ID List.
         * @summary Get ID List Metadata
         * @param {string} id 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdIdlistMetadataGet(id: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdIdlistMetadataGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdIdlistMetadataGet(id, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdIdlistMetadataGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint has a limit of 1000 ids per request
         * @summary Remove IDs from User Store ID List
         * @param {string} id id
         * @param {SegmentIDListUserStoreContractDto} segmentIDListUserStoreContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdRemoveIdsPatch(id: string, segmentIDListUserStoreContractDto: SegmentIDListUserStoreContractDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdIdListDelete200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdRemoveIdsPatch(id, segmentIDListUserStoreContractDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdRemoveIdsPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Commit Segment Review
         * @param {string} id 
         * @param {string} reviewID 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsIdReviewsReviewIDCommitPut(id: string, reviewID: string, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsIdReviewsReviewIDCommitPut200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsIdReviewsReviewIDCommitPut(id, reviewID, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsIdReviewsReviewIDCommitPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create Segment
         * @param {SegmentCreateContractDto} segmentCreateContractDto 
         * @param {string} [xRespectReviewSettings] Optional header to respect review settings for mutation endpoints.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SegmentsPost(segmentCreateContractDto: SegmentCreateContractDto, xRespectReviewSettings?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SegmentsPost201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SegmentsPost(segmentCreateContractDto, xRespectReviewSettings, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsApi.consoleV1SegmentsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SegmentsApi - factory interface
 */
export const SegmentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SegmentsApiFp(configuration)
    return {
        /**
         * 
         * @summary List Segments
         * @param {SegmentsApiConsoleV1SegmentsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsGet(requestParameters: SegmentsApiConsoleV1SegmentsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Getconsolev1segmentsResponse> {
            return localVarFp.consoleV1SegmentsGet(requestParameters.limit, requestParameters.page, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint has a limit of 1000 ids per request
         * @summary Add IDs to User Store ID List
         * @param {SegmentsApiConsoleV1SegmentsIdAddIdsPatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdAddIdsPatch(requestParameters: SegmentsApiConsoleV1SegmentsIdAddIdsPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdAddIdsPatch200Response> {
            return localVarFp.consoleV1SegmentsIdAddIdsPatch(requestParameters.id, requestParameters.segmentIDListUserStoreContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Archive Segment
         * @param {SegmentsApiConsoleV1SegmentsIdArchivePutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdArchivePut(requestParameters: SegmentsApiConsoleV1SegmentsIdArchivePutRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdArchivePut200Response> {
            return localVarFp.consoleV1SegmentsIdArchivePut(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Segment Rules
         * @param {SegmentsApiConsoleV1SegmentsIdConditionalPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdConditionalPost(requestParameters: SegmentsApiConsoleV1SegmentsIdConditionalPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdConditionalPost200Response> {
            return localVarFp.consoleV1SegmentsIdConditionalPost(requestParameters.id, requestParameters.segmentCreateContractDtoRulesInner, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Segment
         * @param {SegmentsApiConsoleV1SegmentsIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdDelete(requestParameters: SegmentsApiConsoleV1SegmentsIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdDelete200Response> {
            return localVarFp.consoleV1SegmentsIdDelete(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Segment
         * @param {SegmentsApiConsoleV1SegmentsIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdGet(requestParameters: SegmentsApiConsoleV1SegmentsIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdGet200Response> {
            return localVarFp.consoleV1SegmentsIdGet(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint is rate limited to 900 requests /15m or 12 requests /10s.
         * @summary Remove IDs from Segment
         * @param {SegmentsApiConsoleV1SegmentsIdIdListDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdIdListDelete(requestParameters: SegmentsApiConsoleV1SegmentsIdIdListDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdIdListDelete200Response> {
            return localVarFp.consoleV1SegmentsIdIdListDelete(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint is rate limited to 100
         * @summary Get IDs in a Segment
         * @param {SegmentsApiConsoleV1SegmentsIdIdListGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdIdListGet(requestParameters: SegmentsApiConsoleV1SegmentsIdIdListGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdIdListGet200Response> {
            return localVarFp.consoleV1SegmentsIdIdListGet(requestParameters.id, requestParameters.limit, requestParameters.page, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint is rate limited to 900 requests /15m or 12 requests /10s.
         * @summary Add IDs to Segment
         * @param {SegmentsApiConsoleV1SegmentsIdIdListPatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdIdListPatch(requestParameters: SegmentsApiConsoleV1SegmentsIdIdListPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdAddIdsPatch200Response> {
            return localVarFp.consoleV1SegmentsIdIdListPatch(requestParameters.id, requestParameters.segmentIDListContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * Warning: Not atomic for big ID lists (> 1000)
         * @summary Reset ID List Segment
         * @param {SegmentsApiConsoleV1SegmentsIdIdListResetPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdIdListResetPost(requestParameters: SegmentsApiConsoleV1SegmentsIdIdListResetPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdIdListResetPost200Response> {
            return localVarFp.consoleV1SegmentsIdIdListResetPost(requestParameters.id, requestParameters.segmentIDListResetContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint gets the metadata of the ID List.
         * @summary Get ID List Metadata
         * @param {SegmentsApiConsoleV1SegmentsIdIdlistMetadataGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdIdlistMetadataGet(requestParameters: SegmentsApiConsoleV1SegmentsIdIdlistMetadataGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdIdlistMetadataGet200Response> {
            return localVarFp.consoleV1SegmentsIdIdlistMetadataGet(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint has a limit of 1000 ids per request
         * @summary Remove IDs from User Store ID List
         * @param {SegmentsApiConsoleV1SegmentsIdRemoveIdsPatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdRemoveIdsPatch(requestParameters: SegmentsApiConsoleV1SegmentsIdRemoveIdsPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdIdListDelete200Response> {
            return localVarFp.consoleV1SegmentsIdRemoveIdsPatch(requestParameters.id, requestParameters.segmentIDListUserStoreContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Commit Segment Review
         * @param {SegmentsApiConsoleV1SegmentsIdReviewsReviewIDCommitPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsIdReviewsReviewIDCommitPut(requestParameters: SegmentsApiConsoleV1SegmentsIdReviewsReviewIDCommitPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsIdReviewsReviewIDCommitPut200Response> {
            return localVarFp.consoleV1SegmentsIdReviewsReviewIDCommitPut(requestParameters.id, requestParameters.reviewID, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create Segment
         * @param {SegmentsApiConsoleV1SegmentsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SegmentsPost(requestParameters: SegmentsApiConsoleV1SegmentsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SegmentsPost201Response> {
            return localVarFp.consoleV1SegmentsPost(requestParameters.segmentCreateContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for consoleV1SegmentsGet operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsGetRequest {
    /**
     * Results per page
     */
    readonly limit?: number

    /**
     * Page number
     */
    readonly page?: number

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdAddIdsPatch operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdAddIdsPatchRequest {
    /**
     * id
     */
    readonly id: string

    readonly segmentIDListUserStoreContractDto: SegmentIDListUserStoreContractDto

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdArchivePut operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdArchivePutRequest {
    /**
     * id
     */
    readonly id: string

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdConditionalPost operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdConditionalPostRequest {
    /**
     * id
     */
    readonly id: string

    readonly segmentCreateContractDtoRulesInner: Array<SegmentCreateContractDtoRulesInner>

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdDelete operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdDeleteRequest {
    /**
     * id
     */
    readonly id: string

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdGet operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdGetRequest {
    /**
     * id
     */
    readonly id: string

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdIdListDelete operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdIdListDeleteRequest {
    /**
     * id
     */
    readonly id: string

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdIdListGet operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdIdListGetRequest {
    readonly id: string

    /**
     * Results per page
     */
    readonly limit?: number

    /**
     * Page number
     */
    readonly page?: number

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdIdListPatch operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdIdListPatchRequest {
    /**
     * id
     */
    readonly id: string

    readonly segmentIDListContractDto: SegmentIDListContractDto

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdIdListResetPost operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdIdListResetPostRequest {
    /**
     * id
     */
    readonly id: string

    readonly segmentIDListResetContractDto: SegmentIDListResetContractDto

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdIdlistMetadataGet operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdIdlistMetadataGetRequest {
    readonly id: string

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdRemoveIdsPatch operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdRemoveIdsPatchRequest {
    /**
     * id
     */
    readonly id: string

    readonly segmentIDListUserStoreContractDto: SegmentIDListUserStoreContractDto

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsIdReviewsReviewIDCommitPut operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsIdReviewsReviewIDCommitPutRequest {
    readonly id: string

    readonly reviewID: string

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * Request parameters for consoleV1SegmentsPost operation in SegmentsApi.
 */
export interface SegmentsApiConsoleV1SegmentsPostRequest {
    readonly segmentCreateContractDto: SegmentCreateContractDto

    /**
     * Optional header to respect review settings for mutation endpoints.
     */
    readonly xRespectReviewSettings?: string
}

/**
 * SegmentsApi - object-oriented interface
 */
export class SegmentsApi extends BaseAPI {
    /**
     * 
     * @summary List Segments
     * @param {SegmentsApiConsoleV1SegmentsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsGet(requestParameters: SegmentsApiConsoleV1SegmentsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsGet(requestParameters.limit, requestParameters.page, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint has a limit of 1000 ids per request
     * @summary Add IDs to User Store ID List
     * @param {SegmentsApiConsoleV1SegmentsIdAddIdsPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdAddIdsPatch(requestParameters: SegmentsApiConsoleV1SegmentsIdAddIdsPatchRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdAddIdsPatch(requestParameters.id, requestParameters.segmentIDListUserStoreContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Archive Segment
     * @param {SegmentsApiConsoleV1SegmentsIdArchivePutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdArchivePut(requestParameters: SegmentsApiConsoleV1SegmentsIdArchivePutRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdArchivePut(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Segment Rules
     * @param {SegmentsApiConsoleV1SegmentsIdConditionalPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdConditionalPost(requestParameters: SegmentsApiConsoleV1SegmentsIdConditionalPostRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdConditionalPost(requestParameters.id, requestParameters.segmentCreateContractDtoRulesInner, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Segment
     * @param {SegmentsApiConsoleV1SegmentsIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdDelete(requestParameters: SegmentsApiConsoleV1SegmentsIdDeleteRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdDelete(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Segment
     * @param {SegmentsApiConsoleV1SegmentsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdGet(requestParameters: SegmentsApiConsoleV1SegmentsIdGetRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdGet(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint is rate limited to 900 requests /15m or 12 requests /10s.
     * @summary Remove IDs from Segment
     * @param {SegmentsApiConsoleV1SegmentsIdIdListDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdIdListDelete(requestParameters: SegmentsApiConsoleV1SegmentsIdIdListDeleteRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdIdListDelete(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint is rate limited to 100
     * @summary Get IDs in a Segment
     * @param {SegmentsApiConsoleV1SegmentsIdIdListGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdIdListGet(requestParameters: SegmentsApiConsoleV1SegmentsIdIdListGetRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdIdListGet(requestParameters.id, requestParameters.limit, requestParameters.page, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint is rate limited to 900 requests /15m or 12 requests /10s.
     * @summary Add IDs to Segment
     * @param {SegmentsApiConsoleV1SegmentsIdIdListPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdIdListPatch(requestParameters: SegmentsApiConsoleV1SegmentsIdIdListPatchRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdIdListPatch(requestParameters.id, requestParameters.segmentIDListContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Warning: Not atomic for big ID lists (> 1000)
     * @summary Reset ID List Segment
     * @param {SegmentsApiConsoleV1SegmentsIdIdListResetPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdIdListResetPost(requestParameters: SegmentsApiConsoleV1SegmentsIdIdListResetPostRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdIdListResetPost(requestParameters.id, requestParameters.segmentIDListResetContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint gets the metadata of the ID List.
     * @summary Get ID List Metadata
     * @param {SegmentsApiConsoleV1SegmentsIdIdlistMetadataGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdIdlistMetadataGet(requestParameters: SegmentsApiConsoleV1SegmentsIdIdlistMetadataGetRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdIdlistMetadataGet(requestParameters.id, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint has a limit of 1000 ids per request
     * @summary Remove IDs from User Store ID List
     * @param {SegmentsApiConsoleV1SegmentsIdRemoveIdsPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdRemoveIdsPatch(requestParameters: SegmentsApiConsoleV1SegmentsIdRemoveIdsPatchRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdRemoveIdsPatch(requestParameters.id, requestParameters.segmentIDListUserStoreContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Commit Segment Review
     * @param {SegmentsApiConsoleV1SegmentsIdReviewsReviewIDCommitPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsIdReviewsReviewIDCommitPut(requestParameters: SegmentsApiConsoleV1SegmentsIdReviewsReviewIDCommitPutRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsIdReviewsReviewIDCommitPut(requestParameters.id, requestParameters.reviewID, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create Segment
     * @param {SegmentsApiConsoleV1SegmentsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SegmentsPost(requestParameters: SegmentsApiConsoleV1SegmentsPostRequest, options?: RawAxiosRequestConfig) {
        return SegmentsApiFp(this.configuration).consoleV1SegmentsPost(requestParameters.segmentCreateContractDto, requestParameters.xRespectReviewSettings, options).then((request) => request(this.axios, this.basePath));
    }
}

