/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ConsoleV1AutotunesPost400Response } from '../models';
// @ts-ignore
import type { ConsoleV1AutotunesPost401Response } from '../models';
// @ts-ignore
import type { ConsoleV1SettingsProjectGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SettingsProjectPost200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SettingsReviewsGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SettingsReviewsPost200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SettingsRolesGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SettingsRolesPost200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SettingsTeamsGet200Response } from '../models';
// @ts-ignore
import type { ConsoleV1SettingsTeamsPost200Response } from '../models';
// @ts-ignore
import type { SettingsProjectContractDto } from '../models';
// @ts-ignore
import type { SettingsReviewsContractDto } from '../models';
// @ts-ignore
import type { SettingsRolesContractDto } from '../models';
// @ts-ignore
import type { SettingsTeamsContractDto } from '../models';
/**
 * SettingsApi - axios parameter creator
 */
export const SettingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Project Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsProjectGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/console/v1/settings/project`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Project Settings
         * @param {SettingsProjectContractDto} settingsProjectContractDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsProjectPost: async (settingsProjectContractDto: SettingsProjectContractDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'settingsProjectContractDto' is not null or undefined
            assertParamExists('consoleV1SettingsProjectPost', 'settingsProjectContractDto', settingsProjectContractDto)
            const localVarPath = `/console/v1/settings/project`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(settingsProjectContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Reviews Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsReviewsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/console/v1/settings/reviews`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Reviews Settings
         * @param {SettingsReviewsContractDto} settingsReviewsContractDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsReviewsPost: async (settingsReviewsContractDto: SettingsReviewsContractDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'settingsReviewsContractDto' is not null or undefined
            assertParamExists('consoleV1SettingsReviewsPost', 'settingsReviewsContractDto', settingsReviewsContractDto)
            const localVarPath = `/console/v1/settings/reviews`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(settingsReviewsContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Roles Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsRolesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/console/v1/settings/roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Roles Settings
         * @param {SettingsRolesContractDto} settingsRolesContractDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsRolesPost: async (settingsRolesContractDto: SettingsRolesContractDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'settingsRolesContractDto' is not null or undefined
            assertParamExists('consoleV1SettingsRolesPost', 'settingsRolesContractDto', settingsRolesContractDto)
            const localVarPath = `/console/v1/settings/roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(settingsRolesContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Teams Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsTeamsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/console/v1/settings/teams`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Teams Settings
         * @param {SettingsTeamsContractDto} settingsTeamsContractDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsTeamsPost: async (settingsTeamsContractDto: SettingsTeamsContractDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'settingsTeamsContractDto' is not null or undefined
            assertParamExists('consoleV1SettingsTeamsPost', 'settingsTeamsContractDto', settingsTeamsContractDto)
            const localVarPath = `/console/v1/settings/teams`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication STATSIG-API-KEY required
            await setApiKeyToObject(localVarHeaderParameter, "STATSIG-API-KEY", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(settingsTeamsContractDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SettingsApi - functional programming interface
 */
export const SettingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SettingsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Project Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SettingsProjectGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SettingsProjectGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SettingsProjectGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettingsApi.consoleV1SettingsProjectGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Project Settings
         * @param {SettingsProjectContractDto} settingsProjectContractDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SettingsProjectPost(settingsProjectContractDto: SettingsProjectContractDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SettingsProjectPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SettingsProjectPost(settingsProjectContractDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettingsApi.consoleV1SettingsProjectPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Reviews Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SettingsReviewsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SettingsReviewsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SettingsReviewsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettingsApi.consoleV1SettingsReviewsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Reviews Settings
         * @param {SettingsReviewsContractDto} settingsReviewsContractDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SettingsReviewsPost(settingsReviewsContractDto: SettingsReviewsContractDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SettingsReviewsPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SettingsReviewsPost(settingsReviewsContractDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettingsApi.consoleV1SettingsReviewsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Roles Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SettingsRolesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SettingsRolesGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SettingsRolesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettingsApi.consoleV1SettingsRolesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Roles Settings
         * @param {SettingsRolesContractDto} settingsRolesContractDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SettingsRolesPost(settingsRolesContractDto: SettingsRolesContractDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SettingsRolesPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SettingsRolesPost(settingsRolesContractDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettingsApi.consoleV1SettingsRolesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Teams Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SettingsTeamsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SettingsTeamsGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SettingsTeamsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettingsApi.consoleV1SettingsTeamsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Teams Settings
         * @param {SettingsTeamsContractDto} settingsTeamsContractDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async consoleV1SettingsTeamsPost(settingsTeamsContractDto: SettingsTeamsContractDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConsoleV1SettingsTeamsPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.consoleV1SettingsTeamsPost(settingsTeamsContractDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SettingsApi.consoleV1SettingsTeamsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SettingsApi - factory interface
 */
export const SettingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SettingsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Project Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsProjectGet(options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SettingsProjectGet200Response> {
            return localVarFp.consoleV1SettingsProjectGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Project Settings
         * @param {SettingsApiConsoleV1SettingsProjectPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsProjectPost(requestParameters: SettingsApiConsoleV1SettingsProjectPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SettingsProjectPost200Response> {
            return localVarFp.consoleV1SettingsProjectPost(requestParameters.settingsProjectContractDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Reviews Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsReviewsGet(options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SettingsReviewsGet200Response> {
            return localVarFp.consoleV1SettingsReviewsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Reviews Settings
         * @param {SettingsApiConsoleV1SettingsReviewsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsReviewsPost(requestParameters: SettingsApiConsoleV1SettingsReviewsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SettingsReviewsPost200Response> {
            return localVarFp.consoleV1SettingsReviewsPost(requestParameters.settingsReviewsContractDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Roles Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsRolesGet(options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SettingsRolesGet200Response> {
            return localVarFp.consoleV1SettingsRolesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Roles Settings
         * @param {SettingsApiConsoleV1SettingsRolesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsRolesPost(requestParameters: SettingsApiConsoleV1SettingsRolesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SettingsRolesPost200Response> {
            return localVarFp.consoleV1SettingsRolesPost(requestParameters.settingsRolesContractDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Teams Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsTeamsGet(options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SettingsTeamsGet200Response> {
            return localVarFp.consoleV1SettingsTeamsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Teams Settings
         * @param {SettingsApiConsoleV1SettingsTeamsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        consoleV1SettingsTeamsPost(requestParameters: SettingsApiConsoleV1SettingsTeamsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConsoleV1SettingsTeamsPost200Response> {
            return localVarFp.consoleV1SettingsTeamsPost(requestParameters.settingsTeamsContractDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for consoleV1SettingsProjectPost operation in SettingsApi.
 */
export interface SettingsApiConsoleV1SettingsProjectPostRequest {
    readonly settingsProjectContractDto: SettingsProjectContractDto
}

/**
 * Request parameters for consoleV1SettingsReviewsPost operation in SettingsApi.
 */
export interface SettingsApiConsoleV1SettingsReviewsPostRequest {
    readonly settingsReviewsContractDto: SettingsReviewsContractDto
}

/**
 * Request parameters for consoleV1SettingsRolesPost operation in SettingsApi.
 */
export interface SettingsApiConsoleV1SettingsRolesPostRequest {
    readonly settingsRolesContractDto: SettingsRolesContractDto
}

/**
 * Request parameters for consoleV1SettingsTeamsPost operation in SettingsApi.
 */
export interface SettingsApiConsoleV1SettingsTeamsPostRequest {
    readonly settingsTeamsContractDto: SettingsTeamsContractDto
}

/**
 * SettingsApi - object-oriented interface
 */
export class SettingsApi extends BaseAPI {
    /**
     * 
     * @summary Get Project Settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SettingsProjectGet(options?: RawAxiosRequestConfig) {
        return SettingsApiFp(this.configuration).consoleV1SettingsProjectGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Project Settings
     * @param {SettingsApiConsoleV1SettingsProjectPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SettingsProjectPost(requestParameters: SettingsApiConsoleV1SettingsProjectPostRequest, options?: RawAxiosRequestConfig) {
        return SettingsApiFp(this.configuration).consoleV1SettingsProjectPost(requestParameters.settingsProjectContractDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Reviews Settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SettingsReviewsGet(options?: RawAxiosRequestConfig) {
        return SettingsApiFp(this.configuration).consoleV1SettingsReviewsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Reviews Settings
     * @param {SettingsApiConsoleV1SettingsReviewsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SettingsReviewsPost(requestParameters: SettingsApiConsoleV1SettingsReviewsPostRequest, options?: RawAxiosRequestConfig) {
        return SettingsApiFp(this.configuration).consoleV1SettingsReviewsPost(requestParameters.settingsReviewsContractDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Roles Settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SettingsRolesGet(options?: RawAxiosRequestConfig) {
        return SettingsApiFp(this.configuration).consoleV1SettingsRolesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Roles Settings
     * @param {SettingsApiConsoleV1SettingsRolesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SettingsRolesPost(requestParameters: SettingsApiConsoleV1SettingsRolesPostRequest, options?: RawAxiosRequestConfig) {
        return SettingsApiFp(this.configuration).consoleV1SettingsRolesPost(requestParameters.settingsRolesContractDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Teams Settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SettingsTeamsGet(options?: RawAxiosRequestConfig) {
        return SettingsApiFp(this.configuration).consoleV1SettingsTeamsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Teams Settings
     * @param {SettingsApiConsoleV1SettingsTeamsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public consoleV1SettingsTeamsPost(requestParameters: SettingsApiConsoleV1SettingsTeamsPostRequest, options?: RawAxiosRequestConfig) {
        return SettingsApiFp(this.configuration).consoleV1SettingsTeamsPost(requestParameters.settingsTeamsContractDto, options).then((request) => request(this.axios, this.basePath));
    }
}

