/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AlertEventSchemaDto {
    /**
     * ID of the alert event
     */
    'id': string;
    /**
     * Type of alert event
     */
    'eventType': AlertEventSchemaDtoEventTypeEnum;
    /**
     * Title of the alert event
     */
    'title': string;
    /**
     * Message for the alert event
     */
    'message': string;
    /**
     * Reason the event was created
     */
    'reason': string;
    /**
     * Timestamp in milliseconds when the event was created
     */
    'createdTime': number;
    /**
     * Group-by values associated with this event
     */
    'multiAlertGroupBys': { [key: string]: string; };
}

export const AlertEventSchemaDtoEventTypeEnum = {
    Raise: 'raise',
    Warn: 'warn',
    Resolve: 'resolve',
    NoData: 'no-data'
} as const;

export type AlertEventSchemaDtoEventTypeEnum = typeof AlertEventSchemaDtoEventTypeEnum[keyof typeof AlertEventSchemaDtoEventTypeEnum];


