/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IngestionSourceCreateContractDtoOneOf1ColumnMapping } from './ingestion-source-create-contract-dto-one-of1-column-mapping';

export interface IngestionSourceCreateContractDtoOneOf1 {
    'dataset': IngestionSourceCreateContractDtoOneOf1DatasetEnum;
    'column_mapping'?: IngestionSourceCreateContractDtoOneOf1ColumnMapping;
    'type': IngestionSourceCreateContractDtoOneOf1TypeEnum;
    'source_name': string;
    'query'?: string;
    'use_delta_sharing'?: boolean;
    'share'?: string;
    'schema'?: string;
    'table'?: string;
    'enabled'?: boolean;
}

export const IngestionSourceCreateContractDtoOneOf1DatasetEnum = {
    Events: 'Events'
} as const;

export type IngestionSourceCreateContractDtoOneOf1DatasetEnum = typeof IngestionSourceCreateContractDtoOneOf1DatasetEnum[keyof typeof IngestionSourceCreateContractDtoOneOf1DatasetEnum];
export const IngestionSourceCreateContractDtoOneOf1TypeEnum = {
    Redshift: 'redshift',
    BigqueryV2: 'bigquery-v2',
    SnowflakeV2: 'snowflake-v2',
    Databricks: 'databricks',
    AzureSynapse: 'azure-synapse',
    S3: 's3',
    Athena: 'athena',
    Adls: 'adls'
} as const;

export type IngestionSourceCreateContractDtoOneOf1TypeEnum = typeof IngestionSourceCreateContractDtoOneOf1TypeEnum[keyof typeof IngestionSourceCreateContractDtoOneOf1TypeEnum];


