/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface IngestionSourceCreateContractDtoOneOf2ColumnMapping {
    /**
     * Unique identifier for the experiment.
     */
    'experiment': string;
    /**
     * Unique identifier for the experiment groups.
     */
    'group_id': string;
    /**
     * The unique user identifier this exposure is for. This might not necessarily be a single column for userID - it could be spread across multiple columns for deviceID etc.
     */
    'unit_id'?: string;
    /**
     * Unix timestamp in seconds of the event (ex. 1613584800)
     */
    'timestamp': string;
    'ids': { [key: string]: string; };
    'metadata'?: { [key: string]: string; };
    'metadata_object'?: string;
    'event_value'?: string;
}

