/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LayerCreateContractDtoTargetApps } from './layer-create-contract-dto-target-apps';

export interface LayerCreateContractDto {
    /**
     * The unique name of the layer, formatted as an ID (e.g., \"A Layer\" becomes \"a_layer\").
     */
    'name': string;
    /**
     * A helpful description of what this layer does, providing context for its purpose.
     */
    'description'?: string;
    /**
     * The type of ID used for this layer, essential for validation in services.
     */
    'idType': string;
    'targetApps'?: LayerCreateContractDtoTargetApps;
    /**
     * Optional identifier for the team responsible for this layer.
     */
    'team'?: string;
}

