/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExternalMetricDefinitionContractDtoWarehouseNativeComponentsInner } from './external-metric-definition-contract-dto-warehouse-native-components-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalMetricDefinitionContractDtoWarehouseNativeFunnelEventsInner } from './external-metric-definition-contract-dto-warehouse-native-funnel-events-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalMetricDefinitionContractDtoWarehouseNativeMetricDimensionLimitsInner } from './external-metric-definition-contract-dto-warehouse-native-metric-dimension-limits-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExternalMetricDefinitionContractDtoWarehouseNativeMetricSourcesInner } from './external-metric-definition-contract-dto-warehouse-native-metric-sources-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { MetricEventsCriteriaDto } from './metric-events-criteria-dto';

/**
 * Optional configuration for metrics utilizing Warehouse Native features, defining specific behaviors and criteria.
 */
export interface MetricsUpdateContractDtoWarehouseNative {
    /**
     * Allowed: count┃sum┃mean┃daily_participation┃ratio┃funnel┃count_distinct┃percentile
     */
    'aggregation'?: MetricsUpdateContractDtoWarehouseNativeAggregationEnum;
    /**
     * For Count, Sum, Mean, User Count aggregation types: the name of metric source
     */
    'metricSourceName'?: string;
    /**
     * Filtering criteria for the metric source
     */
    'criteria'?: Array<MetricEventsCriteriaDto>;
    /**
     * List of metric sources for this metric. This field is readonly.
     */
    'metricSources'?: Array<ExternalMetricDefinitionContractDtoWarehouseNativeMetricSourcesInner>;
    'waitForCohortWindow'?: boolean;
    /**
     * Filtering criteria for the denominator metric source for a ratio, or the start event for a retention metric if useSecondaryRetentionEvent is set
     */
    'denominatorCriteria'?: Array<MetricEventsCriteriaDto>;
    /**
     * Allowed: count┃sum┃mean┃daily_participation┃ratio┃funnel┃count_distinct┃percentile
     */
    'denominatorAggregation'?: MetricsUpdateContractDtoWarehouseNativeDenominatorAggregationEnum;
    /**
     * Custom end window for ratio denominator unit count metrics with \"custom\" rollup time window. Measured in days or minutes depending on the \"denominatorCustomRollupMeasureInMinutes\" flag.
     */
    'denominatorCustomRollupEnd'?: number;
    /**
     * Custom start window for ratio denominator unit count metrics with \"custom\" rollup time window. Measured in days or minutes depending on the \"denominatorCustomRollupMeasureInMinutes\" flag.
     */
    'denominatorCustomRollupStart'?: number;
    /**
     * Name of the metric source for the denominator of a ratio, or the start event for a retention metric if useSecondaryRetentionEvent is set
     */
    'denominatorMetricSourceName'?: string;
    /**
     * Rollup-mode for ratio denominator unit count metrics. Allowed values: \"daily\" for daily participation rate, \"max\" for one-time event, \"custom\" for a custom attribution window
     */
    'denominatorRollupTimeWindow'?: string;
    /**
     * Column name for the denominator’s value.
     */
    'denominatorValueColumn'?: string;
    /**
     * Duration for counting funnel events in days.
     */
    'funnelCalculationWindow'?: number;
    /**
     * Allowed: users┃sessions for distinct count method in funnel events.
     */
    'funnelCountDistinct'?: MetricsUpdateContractDtoWarehouseNativeFunnelCountDistinctEnum;
    /**
     * List of funnel events with associated criteria and identifiers.
     */
    'funnelEvents'?: Array<ExternalMetricDefinitionContractDtoWarehouseNativeFunnelEventsInner>;
    /**
     * Allowed: start_event┃exposure to determine funnel start criteria.
     */
    'funnelStartCriteria'?: MetricsUpdateContractDtoWarehouseNativeFunnelStartCriteriaEnum;
    /**
     * Specify metadata columns for breaking down metric analysis.
     */
    'metricDimensionColumns'?: Array<string>;
    /**
     * Per-dimension breakdown limits; values beyond the limit are grouped into OTHER.
     */
    'metricDimensionLimits'?: Array<ExternalMetricDefinitionContractDtoWarehouseNativeMetricDimensionLimitsInner>;
    /**
     * Number of days for metric baking; specify duration for analysis.
     */
    'metricBakeDays'?: number;
    /**
     * Aggregation type for numerator; Allowed: count┃sum┃mean┃daily_participation┃ratio┃funnel┃count_distinct┃percentile.
     */
    'numeratorAggregation'?: MetricsUpdateContractDtoWarehouseNativeNumeratorAggregationEnum;
    /**
     * Column name representing the metric’s value.
     */
    'valueColumn'?: string;
    /**
     * Threshold value for filtering metrics.
     */
    'valueThreshold'?: number;
    /**
     * Include units which do not have a denominator. Only applicable to ratios.
     */
    'allowNullRatioDenominator'?: boolean;
    'funnelStrictOrdering'?: boolean;
    'funnelUseExposureAsFirstEvent'?: boolean;
    'funnelTimestampAllowanceMs'?: number;
    'funnelTimeToConvert'?: boolean;
    /**
     * High threshold for winsorization; must be between 0 and 1.
     */
    'winsorizationHigh'?: number;
    /**
     * Low threshold for winsorization; must be between 0 and 1.
     */
    'winsorizationLow'?: number;
    'winsorizationHighDenominator'?: number;
    'winsorizationLowDenominator'?: number;
    /**
     * Attribution window for CUPED adjustments in days.
     */
    'cupedAttributionWindow'?: number | null;
    /**
     * Rollup-mode for unit count metrics. Allowed values: \"daily\" for daily participation rate, \"max\" for one-time event, \"custom\" for a custom attribution window
     */
    'rollupTimeWindow'?: string;
    /**
     * Custom start window for unit count metrics with \"custom\" rollup time window, or for other metrics with the \"Use Cohort Window in Experiments\" option on enabled. Measured in days or minutes depending on the \"customRollupMeasureInMinutes\" flag.
     */
    'customRollUpStart'?: number;
    /**
     * Custom end window for unit count metrics with \"custom\" rollup time window, or for other metrics with the \"Use Cohort Window in Experiments\" option on enabled. Measured in days or minutes depending on the \"customRollupMeasureInMinutes\" flag.
     */
    'customRollUpEnd'?: number;
    /**
     * Flag to include only users with a conversion event in the metric.
     */
    'onlyIncludeUsersWithConversionEvent'?: boolean;
    /**
     * Flag to measure the denominator custom rollup window in minutes instead of days.
     */
    'denominatorCustomRollupMeasureInMinutes'?: boolean;
    /**
     * Flag to measure the custom rollup window in minutes instead of days.
     */
    'customRollupMeasureInMinutes'?: boolean;
    /**
     * Percentile value for statistical calculations.
     */
    'percentile'?: number;
    /**
     * Use log transform for the metric.
     */
    'useLogTransform'?: boolean;
    /**
     * Use a different start and completion event for retention calculations.
     */
    'useSecondaryRetentionEvent'?: boolean;
    /**
     * Retention end in days.
     */
    'retentionEnd'?: number;
    /**
     * Retention lookback window in days.
     */
    'retentionLength'?: number;
    /**
     * Log transform base to be used for the metric.
     */
    'logTransformBase'?: number | null;
    /**
     * Maximum cap for metric values.
     */
    'cap'?: number;
    /**
     * Mean Squared Error for surrogate metric.
     */
    'surrogateMetricMSE'?: number | null;
    /**
     * Components for composite metrics, defining each component of the formula
     */
    'components'?: Array<ExternalMetricDefinitionContractDtoWarehouseNativeComponentsInner>;
}

export const MetricsUpdateContractDtoWarehouseNativeAggregationEnum = {
    Count: 'count',
    Sum: 'sum',
    Mean: 'mean',
    DailyParticipation: 'daily_participation',
    Ratio: 'ratio',
    Funnel: 'funnel',
    CountDistinct: 'count_distinct',
    Percentile: 'percentile',
    FirstValue: 'first_value',
    LatestValue: 'latest_value',
    Retention: 'retention',
    Max: 'max',
    Min: 'min',
    Composite: 'composite',
    Empty: ''
} as const;

export type MetricsUpdateContractDtoWarehouseNativeAggregationEnum = typeof MetricsUpdateContractDtoWarehouseNativeAggregationEnum[keyof typeof MetricsUpdateContractDtoWarehouseNativeAggregationEnum];
export const MetricsUpdateContractDtoWarehouseNativeDenominatorAggregationEnum = {
    Count: 'count',
    Sum: 'sum',
    Mean: 'mean',
    DailyParticipation: 'daily_participation',
    Ratio: 'ratio',
    Funnel: 'funnel',
    CountDistinct: 'count_distinct',
    Percentile: 'percentile',
    FirstValue: 'first_value',
    LatestValue: 'latest_value',
    Retention: 'retention',
    Max: 'max',
    Min: 'min',
    Composite: 'composite',
    Empty: ''
} as const;

export type MetricsUpdateContractDtoWarehouseNativeDenominatorAggregationEnum = typeof MetricsUpdateContractDtoWarehouseNativeDenominatorAggregationEnum[keyof typeof MetricsUpdateContractDtoWarehouseNativeDenominatorAggregationEnum];
export const MetricsUpdateContractDtoWarehouseNativeFunnelCountDistinctEnum = {
    Sessions: 'sessions',
    Users: 'users'
} as const;

export type MetricsUpdateContractDtoWarehouseNativeFunnelCountDistinctEnum = typeof MetricsUpdateContractDtoWarehouseNativeFunnelCountDistinctEnum[keyof typeof MetricsUpdateContractDtoWarehouseNativeFunnelCountDistinctEnum];
export const MetricsUpdateContractDtoWarehouseNativeFunnelStartCriteriaEnum = {
    StartEvent: 'start_event',
    Exposure: 'exposure'
} as const;

export type MetricsUpdateContractDtoWarehouseNativeFunnelStartCriteriaEnum = typeof MetricsUpdateContractDtoWarehouseNativeFunnelStartCriteriaEnum[keyof typeof MetricsUpdateContractDtoWarehouseNativeFunnelStartCriteriaEnum];
export const MetricsUpdateContractDtoWarehouseNativeNumeratorAggregationEnum = {
    Count: 'count',
    Sum: 'sum',
    Mean: 'mean',
    DailyParticipation: 'daily_participation',
    Ratio: 'ratio',
    Funnel: 'funnel',
    CountDistinct: 'count_distinct',
    Percentile: 'percentile',
    FirstValue: 'first_value',
    LatestValue: 'latest_value',
    Retention: 'retention',
    Max: 'max',
    Min: 'min',
    Composite: 'composite',
    Empty: ''
} as const;

export type MetricsUpdateContractDtoWarehouseNativeNumeratorAggregationEnum = typeof MetricsUpdateContractDtoWarehouseNativeNumeratorAggregationEnum[keyof typeof MetricsUpdateContractDtoWarehouseNativeNumeratorAggregationEnum];


