/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ParamStoreDtoParametersInnerOneOf10 {
    'ref_type': ParamStoreDtoParametersInnerOneOf10RefTypeEnum;
    /**
     * Parameter Name
     */
    'name': string;
    /**
     * Parameter Type
     */
    'param_type': ParamStoreDtoParametersInnerOneOf10ParamTypeEnum;
    /**
     * Layer Name
     */
    'layer_name': string;
    /**
     * Parameter Name in Layer
     */
    'param_name': string;
}

export const ParamStoreDtoParametersInnerOneOf10RefTypeEnum = {
    Layer: 'layer'
} as const;

export type ParamStoreDtoParametersInnerOneOf10RefTypeEnum = typeof ParamStoreDtoParametersInnerOneOf10RefTypeEnum[keyof typeof ParamStoreDtoParametersInnerOneOf10RefTypeEnum];
export const ParamStoreDtoParametersInnerOneOf10ParamTypeEnum = {
    String: 'string',
    Boolean: 'boolean',
    Number: 'number',
    Array: 'array',
    Object: 'object'
} as const;

export type ParamStoreDtoParametersInnerOneOf10ParamTypeEnum = typeof ParamStoreDtoParametersInnerOneOf10ParamTypeEnum[keyof typeof ParamStoreDtoParametersInnerOneOf10ParamTypeEnum];


