/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PulseLoadHistoryDetailsDtoJobsInner {
    /**
     * The Echidna job type.
     */
    'jobType': string;
    /**
     * Warehouse execution IDs for this job.
     */
    'jobIDs': Array<string>;
    /**
     * Unix timestamp in milliseconds when this job started.
     */
    'startTime': number | null;
    /**
     * Unix timestamp in milliseconds when this job ended, when available.
     */
    'endTime': number | null;
    /**
     * The SQL executed for this job.
     */
    'sql': string | null;
    /**
     * Present for user-metrics style jobs and names the metric source used by the job.
     */
    'metricSourceName'?: string | null;
    /**
     * Present for pulse-style jobs and indicates the rollup used for the calculation.
     */
    'rollup'?: PulseLoadHistoryDetailsDtoJobsInnerRollupEnum | null;
}

export const PulseLoadHistoryDetailsDtoJobsInnerRollupEnum = {
    _7: '7',
    _14: '14',
    _28: '28',
    Cumulative: 'cumulative',
    Dx: 'dx',
    Daily: 'daily',
    PreExposure: 'pre_exposure'
} as const;

export type PulseLoadHistoryDetailsDtoJobsInnerRollupEnum = typeof PulseLoadHistoryDetailsDtoJobsInnerRollupEnum[keyof typeof PulseLoadHistoryDetailsDtoJobsInnerRollupEnum];


