/* tslint:disable */
/* eslint-disable */
/**
 * Console API
 * The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI. If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know. <br /><br /> <b>Authorization</b> <br /> All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys) <br /><br /> <b>Rate Limiting</b> <br /> Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>. <br /><br /> <b>Keyboard Search</b> <br /> Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.
 *
 * The version of the OpenAPI document: 20240601.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PrecommitHookArgsDtoOneOf4OldConfigRulesInner } from './precommit-hook-args-dto-one-of4-old-config-rules-inner';

export interface SegmentDto {
    /**
     * Is the segment enabled.
     */
    'isEnabled': boolean;
    'type': SegmentDtoTypeEnum;
    /**
     * For id_list segments: the length of the ID list
     */
    'count'?: number;
    /**
     * Rule Object
     */
    'rules'?: Array<PrecommitHookArgsDtoOneOf4OldConfigRulesInner>;
    /**
     * Optional tags for categorization.
     */
    'tags'?: Array<string>;
    /**
     * ID
     */
    'id': string;
    /**
     * Optional name for the configuration.
     */
    'name'?: string;
    /**
     * Type of ID
     */
    'idType': string;
    /**
     * Detailed description of the configuration’s purpose.
     */
    'description': string;
    /**
     * ID of the last modifier.
     */
    'lastModifierID': string | null;
    /**
     * Time of the last modification.
     */
    'lastModifiedTime': number | null;
    /**
     * Email of the last modifier.
     */
    'lastModifierEmail': string | null;
    /**
     * Name of the last modifier.
     */
    'lastModifierName': string | null;
    /**
     * ID of the user who created the entity.
     */
    'creatorID': string | null;
    /**
     * Timestamp when the entity was created.
     */
    'createdTime': number;
    /**
     * Name of the creator.
     */
    'creatorName': string | null;
    /**
     * Email of the creator.
     */
    'creatorEmail': string | null;
    /**
     * List of target applications associated with this configuration.
     */
    'targetApps'?: Array<string>;
    /**
     * Holdouts applied to this configuration.
     */
    'holdoutIDs'?: Array<string>;
    /**
     * Optional name for the responsible team.
     */
    'team'?: string | null;
    /**
     * Optional ID of the responsible team.
     */
    'teamID'?: string | null;
    /**
     * Version number
     */
    'version'?: number;
}

export const SegmentDtoTypeEnum = {
    IdList: 'id_list',
    RuleBased: 'rule_based',
    AnalysisList: 'analysis_list',
    UserStoreIdList: 'user_store_id_list'
} as const;

export type SegmentDtoTypeEnum = typeof SegmentDtoTypeEnum[keyof typeof SegmentDtoTypeEnum];


